Regex - Extract all occurence of COVID-19 #2
Data-Epic/intermediate_project pull request #10
Opened 2024-06-07 13:13 UTC by armaf002

This introduces a Python script named "task.py" that utilizes a regular expression (regex) pattern to extract all mentions of the keyword "COVID-19" from a provided text block, regardless of letter casing.

2024-06-08 18:43 UTC, elseagle approved these changes
LGTM! Good Job

2024-06-12 11:23 UTC, hammedb197 commented
@armaf002 can you move your work folder into Regex/

2024-06-12 11:49 UTC, armaf002 commented
@hammedb197 Alright, I'll do that

2024-06-12 13:18 UTC, armaf002 commented
> @armaf002 can you move your work folder into Regex/

@hammedb197 I've moved the folder into Regex/

2024-06-22 18:37 UTC, elseagle requested changes

2024-06-22 18:37 UTC, elseagle commented on Regex/Extract all occurence of COVID-19 #2/README.md
your folder should not have space in it. Use under score and ensure they are lowercase

2024-06-22 18:37 UTC, elseagle commented on ridwan_regex_task/extract_covid19.py
This folder and file should be inside the Regex folder else delete it if not needed

2024-06-22 18:42 UTC, armaf002 commented on Regex/Extract all occurence of COVID-19 #2/README.md
That was my mistake, I'll rectify it

2024-06-22 18:43 UTC, armaf002 commented on ridwan_regex_task/extract_covid19.py
I'll delete all the irrelevant files and folders

2024-06-23 11:58 UTC, armaf002 commented on ridwan_regex_task/extract_covid19.py
All the not needed files has been deleted

2024-06-23 11:58 UTC, armaf002 commented on Regex/Extract all occurence of COVID-19 #2/README.md
It has been rectified

2024-06-27 09:57 UTC, merged