USID regex
Data-Epic/intermediate_project pull request #12
Opened 2024-06-07 16:54 UTC by dammy230

extracting USID numbers from Regex

2024-06-08 19:01 UTC, elseagle requested changes
Good work. Your PR name is confusing : I'm not sure we have any task for `USID`. Do you mean `UUID`?

Also, you were meant to pick just one task - you picked 2.

In addition; your file names have spaces in them and some are uppercase. You should name files with lowercase and join multiple words with an underscore e.g `api_using_file_name`.

Lastly what does `API USING FILE NAME.py` do?

2024-06-10 01:54 UTC, dammy230 commented on API USING FILE NAME.py
> +gc = gspread.service_account(filename=r"copy file path on pc")
Noted.
thank you

2024-06-12 23:44 UTC, closed without merging

2024-06-23 19:32 UTC, elseagle commented on API USING FILE NAME.py
@dammy230 ?

2024-06-23 19:34 UTC, elseagle commented on collecting Kenya phone number.py
> +    print(match)
@dammy230 ?